name: tot_landing_page_widgets
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"
dependencies:
  bloc: null
  bloc_concurrency: ^0.2.2
  bloc_provider: null
  cached_network_image: null
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18
  flutter_phone_direct_caller: ^2.1.1
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.0
  freezed_annotation: null
  get_it: ^7.6.4
  go_router: ^10.1.2
  hive: null
  hive_flutter: ^1.1.0
  intl: null
  json_annotation: null
  logger: ^2.0.2
  path_provider: ^2.1.1
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  tot_atomic_design:
    git:
      url: https://github.com/TOTPLATFORM/flutter-atoms.git
      path: packages/tot_atomic_design
      ref: dev
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: null
  hive_generator: null
  json_serializable: null

flutter:
  uses-material-design: true

  assets:
    - assets/
